language: node_js
node_js:
  - "10"
  - "12"
addons:
  apt:
    config:
      retries: true
script:
  - npm run build
  - npm run lint
  - npm test
after_success:
  - npm run coveralls
cache:
  directories:
    - node_modules
