language: node_js
node_js:
  - "8"
  - "10"
  # - "node" node 12 has still some problems with the hdt module
addons:
  apt:
    config:
      retries: true
script:
  - npm run build
  - npm run lint
  - npm test
after_success:
  - npm run coveralls
cache:
  directories:
    - node_modules
